[pytest]
minversion = 7.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    android: Tests for Android platform
    ios: Tests for iOS platform

addopts =
    -v
    --strict-markers
    --alluredir=allure-results
    --clean-alluredir
    -p no:warnings